const COPY_THEMES = {
  normal: {
    onboardingTitle: 'HÀNH TRÌNH TỈNH THỨC',
    onboardingSubtitle: 'Tập trung, kỷ luật và xây lại sức mạnh nội tâm.',
    onboardingChooseStage: 'Chọn mốc thử thách:',
    onboardingStartButton: 'BẮT ĐẦU HÀNH TRÌNH',
    homeHeaderLabel: '[DỊCH CHUYỂN THỜI GIAN]',
    homeLevelLabel: 'Cấp độ hiện tại',
    homeStartingLevel: 'NGƯỜI MỚI BẮT ĐẦU',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Kỷ luật là tự do."',
    homeFailButton: 'BÁO LỖI (TÔI ĐÃ THẤT BẠI)',
    homeResetButton: 'Làm lại từ đầu',
    leaderboardTitle: 'BẢNG XẾP HẠNG',
    leaderboardSubtitle: 'Những người bền bỉ nhất',
    tabHome: 'Trang Chủ',
    tabLeaderboard: 'Bảng Xếp Hạng',
    tabSettings: 'Cài Đặt',
    settingsTitle: 'Cài Đặt',
    settingsSubtitle: 'Tùy chỉnh phong cách và danh xưng',
    settingsNameLabel: 'Tên hiển thị',
    settingsThemeLabel: 'Chủ đề từ ngữ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Tông thử thách',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập tên hiển thị.',
  },
  xianxia: {
    onboardingTitle: 'CƯƠNG LĨNH TU ĐẠO',
    onboardingSubtitle: 'Hồng trần vạn trượng, một tay buông bỏ, nghịch thiên cải mệnh.',
    onboardingChooseStage: 'Chọn cảnh giới tu luyện:',
    onboardingStartButton: 'BƯỚC VÀO LUÂN HỒI',
    homeHeaderLabel: '[DỊCH CHUYỂN THỜI GIAN]',
    homeLevelLabel: 'Cảnh giới hiện tại',
    homeStartingLevel: 'PHÀM NHÂN TỤC TỬ',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Nghịch thiên nhi hành, tu luyện tâm tính mới là đại đạo."',
    homeFailButton: 'TÂM MA TRỖI DẬY (THẤT BẠI)',
    homeResetButton: 'Nhục nhã bấm làm lại',
    leaderboardTitle: 'BẢNG PHONG THẦN',
    leaderboardSubtitle: 'Thế giới tu tiên',
    tabHome: 'Động Phủ',
    tabLeaderboard: 'Bảng Phong Thần',
    tabSettings: 'Công Pháp',
    settingsTitle: 'Công Pháp',
    settingsSubtitle: 'Tùy chỉnh phong cách và danh xưng',
    settingsNameLabel: 'Danh xưng',
    settingsThemeLabel: 'Chủ đề từ ngữ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Tông thử thách',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập danh xưng.',
  },
};

export const getCopy = (theme) => COPY_THEMES[theme] || COPY_THEMES.xianxia;
