const COPY_THEMES = {
  normal: {
    onboardingTitle: 'GIỮ NHỊP MỖI NGÀY',
    onboardingSubtitle: 'Đi đều từng ngày, giữ mục tiêu rõ ràng và đừng bỏ ngang.',
    onboardingChooseStage: 'Chọn mốc theo dõi:',
    onboardingStartButton: 'BẮT ĐẦU THEO DÕI',
    onboardingHeaderFast1: 'TUA 1 NGÀY',
    onboardingHeaderFast8: 'TUA 8 NGÀY',
    onboardingWarning: 'Nếu bỏ giữa chừng thì cứ làm lại từ đầu, không sao cả.',
    homeHeaderLabel: '[THEO DÕI TIẾN ĐỘ]',
    homeLevelLabel: 'Mốc hiện tại',
    homeStartingLevel: 'NGƯỜI MỚI BẮT ĐẦU',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Kỷ luật là tự do."',
    homeFailButton: 'BÁO ĐÃ TRƯỢT',
    homeResetButton: 'Đặt lại tiến độ',
    homeFastForward1: 'TUA 1 NGÀY',
    homeFastForward8: 'TUA 8 NGÀY',
    leaderboardTitle: 'BẢNG TIẾN ĐỘ',
    leaderboardSubtitle: 'Những người đang đi đều nhất',
    tabHome: 'Trang Chủ',
    tabLeaderboard: 'Bảng Thành Tích',
    tabSettings: 'Thiết Lập',
    settingsTitle: 'Thiết Lập',
    settingsSubtitle: 'Đổi tên, đổi kiểu hiển thị, bật tắt thông báo.',
    settingsNameLabel: 'Tên hiển thị',
    settingsThemeLabel: 'Kiểu ngôn từ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Mức nhắc nhở',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập tên hiển thị.',
  },
  xianxia: {
    onboardingTitle: 'CƯƠNG LĨNH TU ĐẠO',
    onboardingSubtitle: 'Hồng trần vạn trượng, một tay buông bỏ, nghịch thiên cải mệnh.',
    onboardingChooseStage: 'Chọn cảnh giới tu luyện:',
    onboardingStartButton: 'BƯỚC VÀO LUÂN HỒI',
    onboardingHeaderFast1: 'TUA 1 NGÀY',
    onboardingHeaderFast8: 'TUA 8 NGÀY',
    onboardingWarning: 'Bút sa gà chết. Một khi đã chọn con đường này, nếu tâm ma trỗi dậy làm loạn, vạn kiếp bất phục.',
    homeHeaderLabel: '[DỊCH CHUYỂN THỜI GIAN]',
    homeLevelLabel: 'Cảnh giới hiện tại',
    homeStartingLevel: 'PHÀM NHÂN TỤC TỬ',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Nghịch thiên nhi hành, tu luyện tâm tính mới là đại đạo."',
    homeFailButton: 'TÂM MA TRỖI DẬY (THẤT BẠI)',
    homeResetButton: 'Nhục nhã bấm làm lại',
    homeFastForward1: 'TUA 1 NGÀY',
    homeFastForward8: 'TUA 8 NGÀY',
    leaderboardTitle: 'BẢNG PHONG THẦN',
    leaderboardSubtitle: 'Thế giới tu tiên',
    tabHome: 'Động Phủ',
    tabLeaderboard: 'Bảng Phong Thần',
    tabSettings: 'Công Pháp',
    settingsTitle: 'Công Pháp',
    settingsSubtitle: 'Tùy chỉnh phong cách và danh xưng',
    settingsNameLabel: 'Danh xưng',
    settingsThemeLabel: 'Chủ đề từ ngữ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Tông thử thách',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập danh xưng.',
  },
};

export const getCopy = (theme) => COPY_THEMES[theme] || COPY_THEMES.xianxia;
