const COPY_THEMES = {
  normal: {
    onboardingTitle: 'HÀNH TRÌNH GIỮ NHỊP',
    onboardingSubtitle: 'Tập trung, kỷ luật và giữ đúng mục tiêu mỗi ngày.',
    onboardingChooseStage: 'Chọn mốc theo dõi:',
    onboardingStartButton: 'BẮT ĐẦU THEO DÕI',
    onboardingHeaderFast1: 'TUA 1 NGÀY',
    onboardingHeaderFast8: 'TUA 8 NGÀY',
    onboardingWarning: 'Một khi đã chọn mục tiêu này, nếu bỏ giữa chừng thì phải làm lại từ đầu.',
    homeHeaderLabel: '[THEO DÕI TIẾN ĐỘ]',
    homeLevelLabel: 'Mốc hiện tại',
    homeStartingLevel: 'NGƯỜI MỚI BẮT ĐẦU',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Kỷ luật là tự do."',
    homeFailButton: 'ĐÁNH DẤU ĐÃ TRƯỢT',
    homeResetButton: 'Đặt lại tiến trình',
    homeFastForward1: 'TUA 1 NGÀY',
    homeFastForward8: 'TUA 8 NGÀY',
    leaderboardTitle: 'BẢNG THÀNH TÍCH',
    leaderboardSubtitle: 'Những người giữ nhịp tốt nhất',
    tabHome: 'Trang Chủ',
    tabLeaderboard: 'Bảng Thành Tích',
    tabSettings: 'Cài Đặt',
    settingsTitle: 'Cài Đặt',
    settingsSubtitle: 'Tùy chỉnh cách gọi và thiết lập cơ bản',
    settingsNameLabel: 'Tên hiển thị',
    settingsThemeLabel: 'Chủ đề ngôn từ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Tông thông báo',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập tên hiển thị.',
  },
  xianxia: {
    onboardingTitle: 'CƯƠNG LĨNH TU ĐẠO',
    onboardingSubtitle: 'Hồng trần vạn trượng, một tay buông bỏ, nghịch thiên cải mệnh.',
    onboardingChooseStage: 'Chọn cảnh giới tu luyện:',
    onboardingStartButton: 'BƯỚC VÀO LUÂN HỒI',
    onboardingHeaderFast1: 'TUA 1 NGÀY',
    onboardingHeaderFast8: 'TUA 8 NGÀY',
    onboardingWarning: 'Bút sa gà chết. Một khi đã chọn con đường này, nếu tâm ma trỗi dậy làm loạn, vạn kiếp bất phục.',
    homeHeaderLabel: '[DỊCH CHUYỂN THỜI GIAN]',
    homeLevelLabel: 'Cảnh giới hiện tại',
    homeStartingLevel: 'PHÀM NHÂN TỤC TỬ',
    homeTimerLabel: 'NGÀY',
    homeQuote: '"Nghịch thiên nhi hành, tu luyện tâm tính mới là đại đạo."',
    homeFailButton: 'TÂM MA TRỖI DẬY (THẤT BẠI)',
    homeResetButton: 'Nhục nhã bấm làm lại',
    homeFastForward1: 'TUA 1 NGÀY',
    homeFastForward8: 'TUA 8 NGÀY',
    leaderboardTitle: 'BẢNG PHONG THẦN',
    leaderboardSubtitle: 'Thế giới tu tiên',
    tabHome: 'Động Phủ',
    tabLeaderboard: 'Bảng Phong Thần',
    tabSettings: 'Công Pháp',
    settingsTitle: 'Công Pháp',
    settingsSubtitle: 'Tùy chỉnh phong cách và danh xưng',
    settingsNameLabel: 'Danh xưng',
    settingsThemeLabel: 'Chủ đề từ ngữ',
    settingsNotificationsLabel: 'Thông báo',
    settingsToneLabel: 'Tông thử thách',
    settingsSaveButton: 'Lưu thay đổi',
    settingsNoChanges: 'Bạn chưa thay đổi nội dung nào.',
    settingsSaved: 'Cập nhật đã được áp dụng.',
    settingsMissingName: 'Vui lòng nhập danh xưng.',
  },
};

export const getCopy = (theme) => COPY_THEMES[theme] || COPY_THEMES.xianxia;
